### ISSUE TITLE
Error in using the script 

### ISSUE THREAD

**Issue by MrIslamAIman** [raspberrypi5621/pyducky#1]
![Screenshot (73)](https://user-images.githubusercontent.com/16799897/187971354-6e7c2801-703d-43eb-bd9a-bc63fd13893e.png)

**Comment by MrIslamAIman** [comment]
i think because i use windows so every ( cp) needs to be ( copy) and I think I will need to change every (/) to (\\) 
I will try it =D

**Comment by steveiliop56** [comment]
Yeah that's an issue. I will try to recreate the script... I will keep you updated.

**Comment by MrIslamAIman** [comment]
it gives me so many errors =D I am not that good at python =D 
i will wait for ur update =D

**Comment by steveiliop56** [comment]
Hello!!! The script is updated and you can now use it in windows too!!!

**Comment by MrIslamAIman** [comment]
ok that was fast =D thanks man
